
const $=(s,root=document)=>root.querySelector(s);const $$=(s,root=document)=>[...root.querySelectorAll(s)];
$('.menuBtn')?.addEventListener('click',()=>$('.links')?.classList.toggle('open'));
const formSchemas={
weihnachten:{title:'🎄 Weihnachts-Faltkarte',fields:[['child','Name des Kindes ✨','text',true,'So sprechen wir dein Kind persönlich an.'],['age','Alter des Kindes 🎈','number',true,'Hilft uns, Sprache und Ton altersgerecht zu wählen.'],['wishes','Top 3 Weihnachtswünsche 🎁','textarea',true,'Was wünscht sich dein Kind dieses Jahr besonders?'],['pride','Darauf kann dein Kind stolz sein 🌟','textarea',false,'Zum Beispiel: mutig, hilfsbereit, fleissig oder hat etwas Neues gelernt.'],['color','Lieblingsfarbe 🎨','text',false,'Für eine noch persönlichere Magie.'],['figure','Lieblingsfigur / Lieblingsthema 🐻🦄🚀','text',false,'Tier, Fantasiewesen, Märchenfigur oder Held.'],['message','Nachricht an den Weihnachtsmann 🎅','textarea',false,'Eine kleine Botschaft, ein Dankeschön oder ein Wunsch.'],['style','Stil des Weihnachtsbriefes','select',true,'Wähle den Stil, der am besten passt.',['Warm & liebevoll','Lustig & verspielt','Motivierend & bestärkend']],['delivery','Lieferung','select',true,'Wie möchtest du den Brief erhalten?',['PDF per E-Mail','Fertige Faltkarte per Post']]]},
geburtstag:{title:'🎂 Geburtstags-Faltkarte',fields:[['child','Name des Kindes','text',true,''],['age','Alter','number',true,'Wichtig für Ton und Sprache.'],['special','Was macht das Kind besonders?','textarea',false,'Hobbys, Interessen, Charakter.'],['likes','1–3 Lieblingsdinge','textarea',false,'Tiere, Themen, Sport, Figuren.'],['color','Lieblingsfarbe','text',false,''],['pride','Stolz-Moment / besondere Leistung','textarea',false,''],['dream','Geburtstagswunsch / Traum fürs neue Lebensjahr','textarea',false,''],['sender','Absender des Briefes','text',false,'z.B. Deine Geburtstagsfee.'],['style','Stil-Auswahl','select',true,'',['Fröhlich & herzlich','Lustig & verspielt','Bestärkend & motivierend']],['delivery','Lieferung','select',true,'',['PDF per E-Mail','Fertige Faltkarte per Post']]]},
ostern:{title:'🐣 Osterbrief / Osterkarte',fields:[['child','Name des Kindes','text',true,''],['age','Alter','number',true,''],['color','Lieblingsfarbe','text',false,''],['animal','Lieblingstier oder Osterfigur','text',false,'Hase, Küken, Fantasiewesen.'],['activity','Was macht das Kind gerade gern?','textarea',false,''],['pride','Kleine Leistung / Stolz-Moment','textarea',false,''],['wish','Osterwunsch','textarea',false,'Schokolade, Frühling, Überraschung – frei.'],['style','Stil-Auswahl','select',true,'',['Warm & liebevoll','Fröhlich & spielerisch','Sanft motivierend']],['delivery','Lieferung','select',true,'',['PDF per E-Mail','Fertige Faltkarte per Post']]]},
kommunion:{title:'✝️ Kommunion-Erinnerungsbrief',fields:[['child','Name des Kindes','text',true,''],['date','Datum der Kommunion','date',true,''],['traits','Eigenschaften des Kindes','textarea',false,'freundlich, mutig, hilfsbereit.'],['pride','Worauf ist das Kind besonders stolz?','textarea',false,''],['values','Persönliche Werte oder Wünsche der Eltern','textarea',false,'Für den Lebensweg.'],['sender','Absender','text',false,'z.B. Ein beschützender Begleiter.'],['style','Stil-Auswahl','select',true,'',['Feierlich & herzlich','Sanft & bestärkend']],['delivery','Lieferung','select',true,'',['PDF per E-Mail','Fertige Faltkarte per Post']]]},
schultag:{title:'🎒 1. Schultag – Mut & Stolz Brief',fields:[['child','Name des Kindes','text',true,''],['age','Alter / Einschulungsjahr','text',true,''],['joy','Was freut das Kind an der Schule?','textarea',false,''],['fear','Was macht vielleicht noch Angst?','textarea',false,'Hilft beim einfühlsamen Text.'],['strength','Stärke des Kindes','text',false,'neugierig, freundlich, kreativ.'],['colorfigure','Lieblingsfarbe / Lieblingsfigur','text',false,''],['school','Schule oder Klasse','text',false,'Optional.'],['style','Stil-Auswahl','select',true,'',['Mutmachend & liebevoll','Stolz & bestärkend','Leicht & fröhlich']],['delivery','Lieferung','select',true,'',['PDF per E-Mail','Fertige Faltkarte per Post']]]},
motivation:{title:'💖 Motivationsbrief für Kinder',fields:[['child','Name des Kindes','text',true,''],['age','Alter','number',true,''],['situation','Situation','textarea',true,'Prüfung, Streit, wenig Selbstvertrauen – Auswahl oder Freitext.'],['hard','Was fällt dem Kind schwer?','textarea',false,''],['good','Was kann das Kind besonders gut?','textarea',false,''],['trait','Positive Eigenschaft, die betont werden soll','text',false,''],['fantasy','Lieblingsfarbe / Fantasiewesen','text',false,''],['style','Stil-Auswahl','select',true,'',['Sehr liebevoll & tröstend','Mutig & stärkend','Ruhig & beruhigend']],['delivery','Lieferung','select',true,'',['PDF per E-Mail','Fertige Faltkarte per Post']]]}
};
function renderForm(){const sel=$('#eventSelect'), form=$('#magicForm'); if(!sel||!form)return; const schema=formSchemas[sel.value]; form.innerHTML=`<h2 class="field full">${schema.title}</h2>`+schema.fields.map(f=>{let [id,label,type,req,hint,opts]=f;let input= type==='textarea'?`<textarea id="${id}" ${req?'required':''}></textarea>`: type==='select'?`<select id="${id}" ${req?'required':''}>${opts.map(o=>`<option>${o}</option>`).join('')}</select>`:`<input id="${id}" type="${type}" ${req?'required':''}>`;return `<div class="field ${type==='textarea'?'full':''}"><label for="${id}">${label} ${req?'<span style="color:#ff438f">*</span>':'<span class="hint">(optional)</span>'}</label>${input}<small>${hint||''}</small></div>`}).join('')}
$('#eventSelect')?.addEventListener('change',renderForm);
if($('#eventSelect')){const p=new URLSearchParams(location.search); if(p.get('event')) $('#eventSelect').value=p.get('event'); renderForm();}
function formValues(){let vals={}; $$('#magicForm input,#magicForm textarea,#magicForm select').forEach(el=>vals[el.id]=el.value); return vals;}
$('#generateBtn')?.addEventListener('click',()=>{const vals=formValues(), event=$('#eventSelect').value; const name=vals.child||'dein Kind'; const style=vals.style||'warm und liebevoll'; $('#previewBox').innerHTML=`<h4>Liebe/r ${name},</h4><p>dies ist eine erste Druckvorschau für deinen ${formSchemas[event].title}. Der Brief wird ${style.toLowerCase()} formuliert und nimmt die persönlichen Angaben liebevoll auf.</p><p><em>Hier würde im echten System die final generierte Version erscheinen.</em></p><p>Mit funkelnden Grüssen<br>Deine Magische Kinderwelt ✨</p>`});
$('#newVersionBtn')?.addEventListener('click',()=>alert('Demo: Eine neue Version würde erstellt.'));
$('#confirmBtn')?.addEventListener('click',()=>alert('Demo: Bestätigung erhalten. PDF-Erstellung oder Druckauftrag würde nun gestartet.'));
$('#voiceBtn')?.addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){$('#voiceStatus').textContent='Dein Browser unterstützt Spracheingabe leider nicht.';return;} const r=new SR(); r.lang='de-CH'; r.onresult=e=>{const text=e.results[0][0].transcript; const first=$('#magicForm textarea')||$('#magicForm input'); if(first) first.value=(first.value?first.value+' ':'')+text; $('#voiceStatus').textContent='Audio-Text eingefügt.'}; r.start(); $('#voiceStatus').textContent='Ich höre zu…';});
let count=0,total=0;$$('.addCart').forEach(btn=>btn.addEventListener('click',()=>{count++;total+=Number(btn.dataset.price);$('#cartCount').textContent=count;$('#cartTotal').textContent=total;}));
function filterShop(){const q=($('#shopSearch')?.value||'').toLowerCase(), f=$('#shopFilter')?.value||'all'; $$('.product').forEach(p=>{const okText=p.textContent.toLowerCase().includes(q), okTheme=f==='all'||p.dataset.theme===f; p.style.display=okText&&okTheme?'block':'none';});}
$('#shopSearch')?.addEventListener('input',filterShop);$('#shopFilter')?.addEventListener('change',filterShop);
